config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :microposts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  acts_as_taggable
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, length: { maximum: 140 }
  validate  :picture_size
  validates :number, numericality: { only_integer: true, allow_nil: true }

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, '5MB未満である必要があります')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    Micropost.where('user_id = ?', id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  # ユーザーのログインを確認する
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'ログインしてください'
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: :destroy
  before_action :set_locale

  def index
    @user = current_user
    @micropost = Micropost.where(user_id: @user.id)
    @tags = @user.microposts.tag_counts_on(:tags).order('count DESC')
    if params[:tag]
      @tag = params[:tag]
      @micropost = @user.microposts.tagged_with(params[:tag])
    end
  end

  def show
    @microposts = Micropost.find(params[:id])
    @tags = @micropost.tag_counts_on(:tags)
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.update_attributes(micropost_params)
      flash[:success] = '投稿を編集しました‼'
      redirect_to root_url
    else
      @feed_items = []
      render '/microposts/new'
    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      flash[:success] = '投稿を編集しました‼'
      redirect_to root_url
    else
      render '/microposts/edit'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :title, :picture, :number, :tag_list)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

  def set_locale
    I18n.locale = :ja
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'メールとパスワードの組み合わせが無効です'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 10)
      @user = current_user
      @tags = @user.microposts.tag_counts_on(:tags).order('count DESC')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update, :show]

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc).limit(3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'ようこそ、Book Recoへ!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = '更新しました'
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :tag_list)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "Book Reco".freeze
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} | #{BASE_TITLE}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="title">
    <h1>Book Reco</h1>
  </div>
  <nav>
    <div class="menu-item">
      <ul class="navbar-nav navbar-right">
        <li><%= link_to "Home", root_path, class: "no-underline" %></li>
        <% if logged_in? %>
          <li><%= link_to "Settings", edit_user_path(current_user), class: "no-underline" %></li>
          <li><%= link_to "Profile", current_user, class: "no-underline" %></li>
          <li><%= link_to "Log out", logout_path, method: :delete, class: "no-underline" %></li>
          <%= link_to "+", new_micropost_path, class: "btn post-button" %>
        <% else %>
          <li><%= link_to "Sign up", signup_path, class: "no-underline" %></li>
          <li><%= link_to "Log in", login_path, class: "no-underline" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
<div class="clearfix">
  <div class="micropost-left">
    <div class="micropost-picture">
      <figure>
      <% if micropost.picture? %>
        <%= image_tag(micropost.picture.url) %>
      <% else %>
        <image src="/assets/default.png" class="icon" alt="ユーザーアイコン" %>
      <% end %>
      </figure>
    </div>
  </div>
  <div class="micropost-rigth">
    <div class="micropost-title">
      <%= micropost.title %>
    </div>
    <div class="micropost-content">
      <% if micropost.content? %>
        <p><%= micropost.content %></p>
      <% else %>
        <p>no comment</p>
      <% end %>
    </div>
    <div class="micropost-number">
      <p><%= micropost.number %>巻</p>
    </div>
    <div class="micropost-tag">
      <% micropost.tags.each do |tag| %>
        <%= link_to "#{tag.name}", microposts_path(tag: tag.name), class: "no-underline micropots-tag" %>
      <% end %>
    </div>
    <span class="timestamp">
      <%= time_ago_in_words(micropost.created_at) %>前
      <% if current_user?(micropost.user) %>
        <%= link_to "編集", edit_micropost_path(micropost), class: "no-underline" %>
        <%= link_to "削除", micropost, method: :delete, class: "no-underline", data: { confirm: "一度削除すると元に戻すことはできません。削除してもよろしいですか？" } %>
      <% end %>
    </span>
  </div>
</div>
</li>

app/views/microposts/edit.html.erb
<% provide(:title, 'micropost-edit') %>
<%= render 'layouts/header' %>
<div class="micropost">
  <div class="micropost-heading">
    <h2>Micropost Edit</h2>
  </div>
  <%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        フォームには<%= pluralize(@micropost.errors.count, "個のエラーがあります") %>
      </div>
    </div>
  <% end %>
  <div class="edittag-main">
    <div class="edittag-left">
      <div class="edittag-title">
        <%= f.label :書籍タイトル %><br>
        <%= f.text_field :title, autofocus: true, :placeholder =>"#{@micropost.title}" %>
        <% if @micropost.errors.include?(:title) %>
          <p style="color: red;"><%= @micropost.errors.full_messages_for(:title).first %>
        <% end %>
      </div>
      <div class="edittag-number">
        <%= f.label :巻数表示 %><br>
        <%= f.text_field :number, type: 'number', :placeholder =>"#{@micropost.number}" %>
        <% if @micropost.errors.include?(:number) %>
          <p style="color: red;"><%= @micropost.errors.full_messages_for(:number).first %>
        <% end %>
      </div>
      <div class="edittag-tag">
        <%= f.label :カテゴリー %>
        <%= f.text_field :tag_list, value: @micropost.tag_list.join(','), :placeholder =>"#{@micropost.tag_list}" %>
        <% if @micropost.errors.include?(:tag_list) %>
          <p style="color: red;"><%= @micropost.errors.full_messages_for(:tag_list).first %>
        <% end %>
      </div>
      <div class="edittag-content">
        <%= f.label :投稿内容 %><br>
        <%= f.text_field :content, :placeholder =>"#{@micropost.content}" %>
        <% if @micropost.errors.include?(:content) %>
          <p style="color: red;"><%= @micropost.errors.full_messages_for(:content).first %>
        <% end %>
      </div>
    </div>
    <div class="edittag-right">
      <div class="edittag-img">
        <%= f.label :編集前画像 %><br>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        <% if @micropost.picture? %>
          <%= image_tag(@micropost.picture.url) %>
        <% else %>
          <image src="/assets/default.png" class="tag-icon" alt="ユーザーアイコン" %>
        <% end %>
        <% if @micropost.errors.include?(:picture) %>
          <p style="color: red;"><%= @micropost.errors.full_messages_for(:picture).first %>
        <% end %>
      </div>
    </div>
    <div class="edittag-submit"><%= f.submit "更新する" %></div>
  <% end %>
  </div>
</div>

app/views/microposts/index.html.erb
<% provide(:title, 'tag_show') %>
<%= render 'layouts/header' %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
      <div class="home-tag">
        <%= render 'shared/tag_list' %>
      </div>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>【 <%= @tag %> 】</h3>
    <ol class="microposts">
      <%if @micropost.present? %>
        <%= render @micropost %>
      <% end %>
    </ol>
  </div>
</div>

app/views/microposts/new.html.erb
<% provide(:title, 'micropost') %>
<%= render 'layouts/header' %>
<div class="micropost">
  <div class="micropost-heading">
    <h2>Create my Book</h2>
  </div>
  <%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        フォームには<%= pluralize(@micropost.errors.count, "個のエラーがあります") %>
      </div>
    </div>
  <% end %>
  <div class="micropost-main">
    <div class="form-group">
      <%= f.label :title, '書籍タイトル' %>
      <%= f.text_field :title, class: 'form-control', placeholder: "最大文字数: 100" %>
      <small id="title-tip" class="form-text text-muted">
        タイトルを入力してください。
      </small>
      <% if @micropost.errors.include?(:title) %>
        <p style="color: red;"><%= @micropost.errors.full_messages_for(:title).first %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :number, '巻数表示' %>
      <%= f.text_field :number, class: 'form-control', value: '0', type: 'number' %>
      <small id="title-tip" class="form-text text-muted">
        巻数がある場合入力してください。
      </small>
      <% if @micropost.errors.include?(:number) %>
        <p style="color: red;"><%= @micropost.errors.full_messages_for(:number).first %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :tag_list, 'カテゴリー' %>
      <%= f.text_field :tag_list, class: 'form-control', value: @micropost.tag_list.join(','),
          placeholder: "最大文字数: 100" %>
      <small id="title-tip" class="form-text text-muted">
        複数つけるには','で区切ってください。
      </small>
      <% if @micropost.errors.include?(:tag_list) %>
        <p style="color: red;"><%= @micropost.errors.full_messages_for(:tag_list).first %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :content, '投稿内容' %>
      <%= f.text_field :content, class: 'form-control', placeholder: "最大文字数: 140" %>
      <small id="title-tip" class="form-text text-muted">
        補足事項を入力してください。空欄の場合「no comment」と表示されます。
      </small>
      <% if @micropost.errors.include?(:content) %>
        <p style="color: red;"><%= @micropost.errors.full_messages_for(:content).first %>
      <% end %>
    </div>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      <% if @micropost.errors.include?(:picture) %>
        <p style="color: red;"><%= @micropost.errors.full_messages_for(:picture).first %>
      <% end %>
    </span>
    <%= f.submit '投稿', class: 'btn btn-info btn-block' %>
      <small id="submit-tip" class="form-text text-muted">
        投稿する前に投稿内容を見直してください!
      </small>
    <% end %>
  </div>
  <script type="text/javascript">
    $('#micropost_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
    });
  </script>
</div>

app/views/microposts/show.html.erb
<% provide(:title, 'tag_show') %>
<%= render 'layouts/header' %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
      <div class="home-tag">
        <%= render 'shared/tag_list' %>
      </div>
    </section>
  </aside>
  <div class="col-md-8">
    <ol class="microposts">
      <%= render @micropost %>
    </ol>
  </div>
</div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
<% end %>

app/views/shared/_tag_list.html.erb
<div class="tag-main">
  <h1>Tag List</h1>
  <% if @tags.present? %>
    <% @tags.each do |tag| %>
      <div class="tag_list">
        <%=  link_to "#{tag.name}", microposts_path(tag: tag.name), class: "no-underline micropots-tag" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span>所持本数<%= pluralize(current_user.microposts.count, "冊") %></span>

app/views/static_pages/home.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/flash_message' %>
<div class="home-global">
  <% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <div class="home-tag">
        <%= render 'shared/tag_list' %>
      </div>
    </aside>
    <div class="col-md-8">
      <h3>Book Collection</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
  <% else %>
    <div class="home-caption">
      <%= image_tag("home.jpg", alt: "HOME画像") %>
    </div>
    <div class="home-summary">
      <div class="home-main">
        <h1>本屋での重複買い防止！<br>忘れっぽいあなたに捧げる本棚管理アプリ</h1>
        <h2>たくさんの本を所有していると、本屋で「あれ？これ買ったっけ。」<br>「この漫画、何巻まで買ってたっけ。」なんて経験ありませんか？</h2>
        <h2>そんな疑問をすぐに解決してくれるのが「Book Reco」です。</h2>
        <h2>書籍を登録しておくだけで、家にいなくても自分の本棚の中身がわかります。<br>忘れっぽいあなたの代わりに覚えてくれる安心の補助アプリです。</h2>
      </div>
      <div class="home-description">
        <%= link_to "今すぐユーザー登録を行う", signup_path, class: "btn home-button" %>
        <h3>ボタンをクリックしてユーザー登録を開始してください。<br>ユーザー登録は無料です。</h3>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<%= render 'layouts/header' %>
<div class="edit">
  <div class="edit-heading">
    <h1>アカウントを更新</h1>
    <hr class="edit-line">
  </div>
  <div class="edit-main">
    <div class="edit-global">
      <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            フォームには<%= pluralize(@user.errors.count, "個のエラーがあります") %>
          </div>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
        <% if @user.errors.include?(:name) %>
          <p style="color: red;"><%= @user.errors.full_messages_for(:name).first %>
        <% end %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.email_field :email %><br>
        <% if @user.errors.include?(:email) %>
          <p style="color: red;"><%= @user.errors.full_messages_for(:email).first %>
        <% end %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %><br>
        <% if @user.errors.include?(:password) %>
          <p style="color: red;"><%= @user.errors.full_messages_for(:password).first %>
        <% end %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %><br>
        <% if @user.errors.include?(:password_confirmation) %>
          <p style="color: red;"><%= @user.errors.full_messages_for(:password_confirmation).first %>
        <% end %>
      </div>
      <%= f.submit "変更を保存", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<%= render 'layouts/flash_message' %>
<div class="signup">
  <div class="signup-heading">
  <h1>Sign up</h1>
  </div>
  <div class="signup-main">
    <h2>アカウント作成</h2>
  </div>
  <div class="Registration">
  <%= form_for(@user, url: signup_path) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        フォームには<%= pluralize(@user.errors.count, "個のエラーがあります") %>
      </div>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: '田中 太郎' %>
      <% if @user.errors.include?(:name) %>
        <p style="color: red;"><%= @user.errors.full_messages_for(:name).first %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email, placeholder: 'BookReco@example.co.jp' %><br>
      <% if @user.errors.include?(:email) %>
        <p style="color: red;"><%= @user.errors.full_messages_for(:email).first %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password, placeholder: '最小: 6' %><br>
      <% if @user.errors.include?(:password) %>
        <p style="color: red;"><%= @user.errors.full_messages_for(:password).first %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, placeholder: 'パスワード確認' %><br>
      <% if @user.errors.include?(:password_confirmation) %>
        <p style="color: red;"><%= @user.errors.full_messages_for(:password_confirmation).first %>
      <% end %>
    </div>
      <%= f.submit "新規登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= render 'layouts/header' %>
<%= render 'layouts/flash_message' %>
<div class="Profile">
  <aside class="col-md-4">
    <div class="Profile_main">
      <div class="Profile_title">
        <p><%= current_user.name %>さんの最近の投稿</p>
      </div>
    </div>
    <div class="Profile_heading">
      <h2>所持本数<%= pluralize(current_user.microposts.count, "冊") %></h2>
    </div>
    <% if @user.microposts.any? %>
    <div class="Profile_foot">
      <% @microposts.each do |micropost| %>
        <div class="Profile_microposts">
          <div class="Profile_section">
            <p1><%= micropost.title %></p1><br>
            <p2><%= micropost.created_at %></p2>
          </div>
          <div>
            <% if micropost.picture? %>
              <%= image_tag(micropost.picture.url, size: '300x400' )  %>
            <% else %>
              <image src="/assets/default.png" class="Profile_icon" alt="ユーザーアイコン"  %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </aside>
</div>